config/routes.rb
Rails.application.routes.draw do
  get 'location/index'
  get 'tag/index'
  get 'about/index'
  get 'comment/index'
  get 'photo/index'
  get 'album/index'
  get '/search', to: 'album#show'
  # get 'welcome/index'
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :pages

  get '/static/:permalink', to: 'pages#permalink', as: 'permalink'

  resources :about, only: :index
  # get /appointments, to: 'appointments#index'

  resources :album, only: %i[index show]
  # ^ This command creates the same routes as the following two:
  # get '/houses', to: 'houses#index'
  # get '/houses/:id', to: 'houses#show', id: /\d+/
  resources :location, only: %i[index show]

  resources :photo, only: :show
  # get '/photo/:id', to: 'photo#show', id: /\d+/

  resources :comment, only: :show
  # get '/teachers/:id', to: 'teachers#show', id: /\d+/

  root to: 'album#index'


end

app/models/album.rb
class Album < ApplicationRecord
  has_many :photos
  # validates :title, :description, :view, presence: true
  # validates :id, numericality: { only_integer: true }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # validates :postdate, :content, presence: true

end

app/models/location.rb
class Location < ApplicationRecord
  has_many :locations
  # validates :name, :shortname, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :comments
  has_many :tags

  # validates :title, :description, :privacy, :view, :imagePath, presence: true
  # validates :view, numericality: { only_integer: true }
end

app/models/tag.rb
class Tag < ApplicationRecord
  # validates :title, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
	def index
		@pagy, @album =
		if params[:title]
			pagy(Album.where('name LIKE ?', "%#{params[:title]}%"), items: 5)
		else
			pagy(Album.all, time: 10)
		end

	end

		# Automagically load up the associated view.
		# app/views/houses/index.html.erb
		# All instance variables are shared with the view.

	def show
		@album = Album.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
	def index
		@pagy, @location =
		if params[:name]
			pagy(Location.where('name LIKE ?', "%#{params[:name]}%"), items: 5)
		else
			pagy(Location.all, time: 15)
		end
	end
	def show

		# @photo = Photo.find(params[:id])
		@location = Location.find(params[:id])
		# @photo = Photo.find(params[:@location.shortname])
	end
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
		@pagy, @photo =
		if params[:title]
			pagy(Photo.where('name LIKE ?', "%#{params[:title]}%"), items: 5)
		else
			pagy(Photo.all, time: 10)
		end
	end

		# Automagically load up the associated view.
		# app/views/houses/index.html.erb
		# All instance variables are shared with the view.

	def show
		@photo = Photo.find(params[:id])
	end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/album/index.html.erb
<h1>Welcome Album Webstie!</h1>
<p>Lets browse Album</p>


<% if @album.count == 0 %>
  <p>There are no album found</p>
<% else %>
    <%= form_tag album_index_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
      </p>
    <% end %>

    <% @album.each do |album| %>
      <h2><%= album.title %></h2>
      <p> Description:<%= album.description %></p>
      <p>For a list of photo in this album, <%= link_to 'click here', album %>.</p>
    <% end %>
  <% end %>


  <div class="container-fluid" >
    <div class="row col-md-12 mt-5">
      <div class="col-md-8">
        <div class="col-md-4">
          <%== pagy_bootstrap_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>

app/views/album/show.html.erb
<h2><%= @album.title %></h2>

<p>This alblum is for <%=@album.description%></p>
<h3>photos</h3>
<ul>
  <% @album.photos.each do |album| %>
    <li><%= link_to album.title, album %></li>

    <%= image_tag( album.imagePath , width:'200px') %>
    <li><%=album.imagePath%></li>

    <% end %>
</ul>



<p><%= link_to 'Home', root_path %></p>

app/views/comment/index.html.erb
<h1>Comment#index</h1>
<p>Find me in app/views/comment/index.html.erb</p>

app/views/location/index.html.erb
<h1>Location List</h1>
<% if @location.count == 0 %>
  <p>There are no location found</p>
<% else %>
  <% @location.each do |location| %>
    <h2><%= location.shortname %></h2>
    <p> Name: <%= link_to location.name, location %></p>
  <% end %>
<% end %>

  <div class="container-fluid" >
    <div class="row col-md-12 mt-5">
      <div class="col-md-8">
        <div class="col-md-4">
          <%== pagy_bootstrap_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>

app/views/location/show.html.erb
<h2>Location show page</h2>

<p>location name is <%= @location.name %></p>
<p>location short name is <%= @location.shortname %></p>

app/views/photo/index.html.erb
<h1>Photos</h1>
<p>Find me in app/views/photo/index.html.erb</p>

<% @photo.each do |photo| %>

  <%= image_tag( photo.imagePath , width:'200px') %>
  <p>Title : <%= photo.title %> </p>
<% end %>

app/views/photo/show.html.erb
<h2>Detail <%= @photo.title %> Page</h2>

<p>This photo is for <%=@photo.description%></p>
<h3>photos</h3>
<%= image_tag( @photo.imagePath , width:'200px') %>
Photo Id: <%=@photo.id%>
Album Id: <%=@photo.album_id%>




<p><%= link_to 'Home', root_path %></p>

app/views/tag/index.html.erb
<h1>Tag#index</h1>
<p>Find me in app/views/tag/index.html.erb</p>