config/routes.rb
Rails.application.routes.draw do
  get 'location/index'
  get 'tag/index'
  get 'about/index'
  get 'comment/index'
  get 'photo/index'
  get 'album/index'
  get '/search', to: 'album#show'
  # get 'welcome/index'
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :pages

  get '/static/:permalink', to: 'pages#permalink', as: 'permalink'

  resources :about, only: :index
  # get /appointments, to: 'appointments#index'

  resources :album, only: %i[index show]
  # ^ This command creates the same routes as the following two:
  # get '/houses', to: 'houses#index'
  # get '/houses/:id', to: 'houses#show', id: /\d+/
  resources :location, only: %i[index show]

  resources :photo, only: :show
  # get '/photo/:id', to: 'photo#show', id: /\d+/

  resources :comment, only: :show
  # get '/teachers/:id', to: 'teachers#show', id: /\d+/

  root to: 'album#index'


end

app/models/album.rb
class Album < ApplicationRecord
  has_many :photos
  # validates :title, :description, :view, presence: true
  # validates :id, numericality: { only_integer: true }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # validates :postdate, :content, presence: true

end

app/models/location.rb
class Location < ApplicationRecord
  has_many :locations
  # validates :name, :shortname, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :comments
  has_many :tags

  # validates :title, :description, :privacy, :view, :imagePath, presence: true
  # validates :view, numericality: { only_integer: true }
end

app/models/tag.rb
class Tag < ApplicationRecord
  # validates :title, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
	def index
		@pagy, @album =
		if params[:title]
			pagy(Album.where('name LIKE ?', "%#{params[:title]}%"), items: 5)
		else
			pagy(Album.all, time: 10)
		end

	end

		# Automagically load up the associated view.
		# app/views/houses/index.html.erb
		# All instance variables are shared with the view.

	def show
		@album = Album.find(params[:id])
	end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
  end
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
		@pagy, @photo =
		if params[:title]
			pagy(Photo.where('name LIKE ?', "%#{params[:title]}%"), items: 5)
		else
			pagy(Photo.all, time: 10)
		end
	end

		# Automagically load up the associated view.
		# app/views/houses/index.html.erb
		# All instance variables are shared with the view.

	def show
		@photo = Photo.find(params[:id])
	end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Album</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Photo', photo_index_url %></li>
        <li><%= link_to 'Location', location_index_url %></li>
        <li><%= link_to 'Tag', tag_index_url %></li>
        <li><%= link_to 'Comment', comment_index_url %></li>
        <li><%= link_to 'About', about_index_url %></li>

      </ul>
    </nav>
  </header>

    <%= yield %>
  </body>
</html>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @page.title %>
</h1>

<p>
  <%= @page.content %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>